name: Feature Request
description: Suggest a new feature for the project
title: "[Feature Request]: "
labels: [feature request]
body:
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: "Provide a short title for the feature request"
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a detailed description of the feature, including why it is needed and any potential implementation details."
      placeholder: "Describe your feature request here"
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "Select the priority level for this feature"
      options:
        - Low
        - Medium
        - High
      required: true
